[env:hydra_e22]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = no_ota.csv
board_build.filesystem = spiffs
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = dio
upload_speed = 921600
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit GFX Library@^1.11.9
  adafruit/Adafruit SSD1306@^2.5.9
  rweather/Crypto@^0.4.0
build_unflags =
  -Werror=reorder
build_flags =
  -D BOARD_MODEL=0x46
  -Wno-unused-variable
  -Wno-maybe-uninitialized
  -Wno-reorder
